### ISSUE TITLE
运行的时候报错

### ISSUE THREAD

**Issue by lxq1** [chenjiandongx/sniffer#1]
sudo yum install libpcap libpcap-devel
然后执行文件的时候提示这个 
./sniffer 
./sniffer: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./sniffer)

**Comment by chenjiandongx** [comment]
这个是 glibc 版本不匹配的问题 这个项目依赖 `gopacket` 第三方库 该库需要 cgo 调用 所以运行的时候需要与运行环境绑定的 glibc 版本 也就是说要使用 `sniffer` 的话最好自己使用 `go install` 或者 `go get` 命令安装

**Comment by lxq1** [comment]
解决 /lib64/libc.so.6: version `GLIBC_2.15' not found 问题_huaishuming的专栏-CSDN博客
https://blog.csdn.net/huaishuming/article/details/102900254

我们查找了网上的办法，发现升级GLIBC的版本风险也很大，不排除很多小白用户不可用

**Comment by chenjiandongx** [comment]
这个我之前也试过，不过最好还是在环境里装 go，构建完传输二进制到其他相同版本的服务器去使用，直接修改 glibc 不太优雅

2.15 这个版本应该是我构建的那台 centos 的 glibc 的版本
