### ISSUE TITLE
No available devices found on Raspberry Pi 4

### ISSUE THREAD

**Issue by AlterMax** [chenjiandongx/sniffer#4]
Hi !
I run the sniffer version v0.6.0  on my Raspberry Pi 4 with OS Raspbian v10(buster).
After start i get message:
Start sniffer failed: no available devices found

I try to run with key  --all-devices but the result is same message "Start sniffer failed: no available devices found"

**Comment by chenjiandongx** [comment]
@AlterMax try to run the cmd with root privilege
